spring:
  application:
    name: eureka_register-service-ha

---
spring:
#  指定profile=peer1, 当启动参数 --spring.profiles.active=peer1 ，默认使用的是该区域的参数设置
  profiles: peer1
server:
  port: 8761
eureka:
  instance:
#    指定当profile=peer1时,主机名是peer1
    hostname: peer1
#  server:
#    #    关闭自我保护
#    enable-self-preservation: false
#    #清理服务器
#    eviction-interval-timer-in-ms: 5000
  client:
    service-url:
#      将自己注册到peer2这个Eureka上面去
      defaultZone: http://peer2:8762/eureka/

---
spring:
  profiles: peer2
server:
  port: 8762
eureka:
  instance:
    hostname: peer2
  client:
    service-url:
      defaultZone: http://peer1:8761/eureka/
